module.exports = 
{
	"ajxpResourcesFolder" : "module\/ui\/main",
	"zipEnabled" : true,
	"multipleFilesDownloadEnabled" : true,
	"customWording" : {
		"welcomeMessage" : "",
		"title" : "AjaXplorer",
		"icon" : "module\/ui\/main\/Logo250.png",
		"iconWidth" : "250px",
		"iconHeight" : "50px",
		"iconOnly" : true,
		"titleFontSize" : ""
	},
	"usersEnabled" : true,
	"loggedUser" : false,
	"currentLanguage" : "en",
	"session_timeout" : 1440,
	"client_timeout" : 1440,
	"client_timeout_warning" : 3,
	"availableLanguages" : {
		"ca" : "Catalan",
		"cs" : "\u010ce\u0161tina",
		"da" : "Danish",
		"de" : "Deutsch",
		"en" : "English",
		"es" : "Espa\u00f1ol",
		"eus" : "Euskaraz",
		"fi" : "Finnish",
		"fr" : "Fran\u00e7ais",
		"gr" : "\u0395\u03bb\u03bb\u03b7\u03bd\u03b9\u03ba\u03ac",
		"he" : "\u05e2\u05d1\u05e8\u05d9\u05ea",
		"hu" : "Hungarian",
		"it" : "Italiano",
		"ja" : "\u65e5\u672c\u8a9e",
		"kr" : "\ud55c\uad6d\uc5b4",
		"nl" : "Nederlands",
		"no" : "Norwegian",
		"pl" : "Polski",
		"pt-br" : "Portugu\u00eas Brasileiro",
		"ru" : "Russian",
		"si" : "Sloven\u0161\u010dina",
		"sv" : "Svenska",
		"tr" : "T&uuml;rk&#231;e",
		"zh-tw" : "\u7e41\u9ad4\u4e2d\u6587",
		"zh" : "\u7b80\u4f53\u4e2d\u6587"
	},
	"usersEditable" : true,
	"ajxpVersion" : "4.0.4",
	"ajxpVersionDate" : "2012\/03\/02",
	"i18nMessages" : {
		"ajxp_conf.1" : "Configuration Data",
		"ajxp_conf.2" : "Users",
		"ajxp_conf.3" : "Repositories",
		"ajxp_conf.4" : "Logs",
		"ajxp_conf.5" : "Diagnostic",
		"ajxp_conf.6" : "User Name",
		"ajxp_conf.7" : "Is Admin",
		"ajxp_conf.8" : "Repository Label",
		"ajxp_conf.9" : "Access Type",
		"ajxp_conf.10" : "Meta Sources",
		"ajxp_conf.11" : "Add a source",
		"ajxp_conf.12" : "Meta Plugin",
		"ajxp_conf.13" : "Are you sure you want to delete this source?",
		"ajxp_conf.14" : "True",
		"ajxp_conf.15" : "False",
		"ajxp_conf.16" : "Fle Date",
		"ajxp_conf.17" : "Date",
		"ajxp_conf.18" : "I.P.",
		"ajxp_conf.19" : "Level",
		"ajxp_conf.20" : "User",
		"ajxp_conf.21" : "Action",
		"ajxp_conf.22" : "Params",
		"ajxp_conf.23" : "Test Name",
		"ajxp_conf.24" : "Test Data",
		"ajxp_conf.25" : "Repositories Access",
		"ajxp_conf.26" : "Modify Password",
		"ajxp_conf.27" : "Admin Right",
		"ajxp_conf.28" : "User has admin rights?",
		"ajxp_conf.29" : "Read",
		"ajxp_conf.30" : "Write",
		"ajxp_conf.32" : "Repository Driver",
		"ajxp_conf.33" : "Loading...",
		"ajxp_conf.34" : "Are you sure you want to delete this user? This operation is not reversible!",
		"ajxp_conf.35" : "Are you sure you want to delete this repository? This operation is not reversible!",
		"ajxp_conf.36" : "Mandatory fields are missing!",
		"ajxp_conf.37" : "Warning, password and confirmation differ!",
		"ajxp_conf.38" : "Please fill the login field!",
		"ajxp_conf.39" : "Please fill both password fields!",
		"ajxp_conf.40" : "Please check the box to confirm!",
		"ajxp_conf.41" : "Driver Options",
		"ajxp_conf.42" : "Please choose a driver!",
		"ajxp_conf.43" : "User already exists, please choose another login!",
		"ajxp_conf.44" : "User created successfully",
		"ajxp_conf.45" : "Changed admin right for user ",
		"ajxp_conf.46" : "Changed right for user ",
		"ajxp_conf.47" : "Saved data for user ",
		"ajxp_conf.48" : "Password changed successfully for user ",
		"ajxp_conf.49" : "Cannot update password",
		"ajxp_conf.50" : "Error: a repository with the same name already exists",
		"ajxp_conf.51" : "The conf directory is not writeable",
		"ajxp_conf.52" : "Successfully created repository",
		"ajxp_conf.53" : "Error while trying to edit repository",
		"ajxp_conf.54" : "Successfully edited repository",
		"ajxp_conf.55" : "Warning, at the moment, you can only add one instance of each meta plugin.",
		"ajxp_conf.56" : "Successfully added meta source",
		"ajxp_conf.57" : "Successfully deleted meta source",
		"ajxp_conf.58" : "Successfully edited meta source",
		"ajxp_conf.59" : "Successfully deleted repository",
		"ajxp_conf.60" : "User successfully erased",
		"ajxp_conf.61" : "Wrong arguments!",
		"ajxp_conf.62" : "Rights Summary",
		"ajxp_conf.63" : "All",
		"ajxp_conf.64" : "Changed right for role ",
		"ajxp_conf.65" : "Role already exists, choose another name!",
		"ajxp_conf.66" : "Role successfully created",
		"ajxp_conf.67" : "Cannot find role ",
		"ajxp_conf.68" : "Successfully deleted role",
		"ajxp_conf.69" : "Roles",
		"ajxp_conf.70" : "User Roles",
		"ajxp_conf.71" : "Available Roles",
		"ajxp_conf.72" : "Drag'n'drop roles to assign them to the user",
		"ajxp_conf.73" : "Role added to user ",
		"ajxp_conf.74" : "Role deleted from user ",
		"ajxp_conf.75" : "New Role",
		"ajxp_conf.role_access" : "o",
		"ajxp_conf.76" : "Role Id",
		"ajxp_conf.77" : "Access Control",
		"ajxp_conf.78" : "Personal data",
		"ajxp_conf.79" : "Repository",
		"ajxp_conf.80" : "Fine-tune access for this user",
		"ajxp_conf.81" : "Specific repositories data",
		"ajxp_conf.82" : "Batch-edit users",
		"ajxp_conf.83" : "Drag'n'drop roles to apply them to all selected users (shared users are skipped)",
		"ajxp_conf.84" : "Users Roles",
		"ajxp_conf.85" : "Manual actions filtering",
		"ajxp_conf.86" : "list of comma-separated actions that will be disabled for this role, no matter the access right.",
		"ajxp_conf.87" : "Successfully updated actions for this role",
		"ajxp_conf.88" : "This repository is defined in the config file, you cannot edit its meta sources via the GUI.",
		"ajxp_conf.89" : "User specific data",
		"ajxp_conf.90" : "Repository",
		"ajxp_conf.91" : "Template",
		"ajxp_conf.92" : "Create a new template",
		"ajxp_conf.93" : "Edit",
		"ajxp_conf.94" : "Batch Edit",
		"ajxp_conf.95" : "Choose a label and a driver to access the data (check all sections for mandatory fields, you can hover the options labels with your mouse to get more info).",
		"ajxp_conf.96" : "Once a label and driver selected, enable the fields you want to be prefilled in the template using the checkboxes. The other fields will be left to the user. You can enable some fields and leave them empty, if you still want to hide them from the user.",
		"ajxp_conf.repository_access_key" : "N",
		"ajxp_conf.97" : "Plugin options successfully updated",
		"ajxp_conf.98" : "Core Configs",
		"ajxp_conf.99" : "Plugins",
		"ajxp_conf.100" : "Common '%s' plugins options",
		"ajxp_conf.101" : "Name",
		"ajxp_conf.102" : "Identifier",
		"ajxp_conf.103" : "Description",
		"ajxp_conf.104" : "Enabled",
		"ajxp_conf.105" : "Automatic checks",
		"ajxp_conf.106" : "Unique Identifier",
		"ajxp_conf.107" : "Plugin Configurations",
		"ajxp_conf.108" : "Documentation",
		"ajxp_conf.109" : "Global Configurations",
		"ajxp_conf.110" : "Repositories & Users",
		"ajxp_conf.111" : "Logs & Other Data",
		"ajxp_conf.112" : "<b>Apply this role by default<\/b> to all new users.",
		"ajxp_conf.113" : "Role status was successfully modified",
		"ajxp_conf.114" : "Default",
		"ajxp_shared.1" : "Shared Users",
		"ajxp_shared.2" : "Shared Repositories",
		"ajxp_shared.3" : "Public files",
		"ajxp_shared.4" : "File Path",
		"ajxp_shared.5" : "Repository",
		"ajxp_shared.6" : "Password",
		"ajxp_shared.7" : "Expiration",
		"ajxp_shared.8" : "Elements",
		"ajxp_shared.9" : "Associated users",
		"ajxp_shared.10" : "Associated repositories",
		"ajxp_shared.11" : "Are you sure that you want to delete the selected element(s)?",
		"ajxp_shared.12" : "You don't have the permission to delete this element.",
		"ajxp_shared.13" : "Successfully deleted public file.",
		"ajxp_shared.14" : "Integrity",
		"ajxp_shared.15" : "Ok",
		"ajxp_shared.16" : "Broken",
		"ajxp_shared.17" : "Download URL",
		"ajxp_shared.18" : "Copy URL",
		"ajxp_shared.19" : "Copy url to send by email.",
		"ajxp_shared.20" : "Downloads",
		"ajxp_shared.21" : "Yes",
		"ajxp_shared.22" : "No",
		"ajxp_shared.23" : "Successfully deleted %s files.",
		"ajxp_shared.24" : "Nothing to delete.",
		"ajxp_shared.25" : "Clear Expired",
		"ajxp_shared.26" : "Delete expired shared files.",
		"ajxp_shared.27" : "Owner",
		"ajxp_shared.28" : "Files shared for direct download, either protected by a password or not.",
		"ajxp_shared.29" : "Delegates repositories created by users.",
		"ajxp_shared.30" : "Users created to access the delegated repositories.",
		"ajxp_shared.31" : "Description",
		"ajxp_shared.32" : "Reset",
		"ajxp_shared.33" : "Reset download counter",
		"jsapi.1" : "Classes and Interfaces",
		"jsapi.2" : "Properties and Methods",
		"jsapi.3" : "Source File",
		"sql.1" : "Create Table",
		"sql.2" : "Type your SQL query here",
		"sql.3" : "Search",
		"sql.4" : "Clear",
		"wms.1" : "Name",
		"wms.2" : "Title",
		"wms.3" : "Queryable",
		"wms.4" : "Style",
		"wms.5" : "Keywords",
		"wms.6" : "Projection",
		"ios_gui.1.ios" : "There is a native application available for accessing %s through iPhone\/iPad!",
		"ios_gui.2.ios" : "I have it already, open it and add this server to my remote servers",
		"ios_gui.3.ios" : "I don't have it, send me to the App Store now!",
		"ios_gui.4.ios" : "I don't care, let me use the web version of %s.",
		"ios_gui.1.android" : "There is a native AjaXplorer client available for accessing %s on Android OS.",
		"ios_gui.2.android" : "I have it already, open it and add this server to my preconfigured remote servers",
		"ios_gui.3.android" : "I don't have it, send me to the Android Market now!",
		"ios_gui.4.android" : "I don't care, let me use the web version of %s.",
		"code_mirror.1" : "Source Editor",
		"code_mirror.2" : "CodeMirror Syntax Highlighter",
		"code_mirror.3" : "Wrapping",
		"code_mirror.3b" : "Toggle lines wrapping",
		"code_mirror.4" : "Numbers",
		"code_mirror.5" : "Toggle lines numbers",
		"code_mirror.6" : "Jump to line",
		"code_mirror.7" : "Undo",
		"code_mirror.8" : "Redo",
		"code_mirror.9" : "Text Search",
		"code_mirror.10" : "Indent size",
		"openbrowser.1" : "External window",
		"openbrowser.2" : "External browser window",
		"openbrowser.3" : "Opening file in external window, please wait, this window should close automatically.",
		"editor.eml.name" : "Email Viewer",
		"editor.eml.title" : "Email Viewer",
		"editor.eml.1" : "From",
		"editor.eml.2" : "To",
		"editor.eml.3" : "Subject",
		"editor.eml.4" : "Date",
		"editor.eml.5" : "Attachments",
		"editor.eml.6" : "Download EML",
		"editor.eml.7" : "Attachment %s was successfully copied to %s",
		"editor.eml.8" : "Could not open destination file!",
		"editor.eml.9" : "Could not find attachment!",
		"editor.eml.10" : "Download ",
		"editor.eml.11" : "Copy attachment on the server",
		"editor.eml.12" : "Cc",
		"editor.exif.1" : "Exif Reader",
		"editor.exif.2" : "Display Exif data",
		"openlayer.1" : "OpenLayers Map",
		"openlayer.2" : "Filter",
		"openlayer.3" : "Position",
		"openlayer.4" : "Layers",
		"openlayer.5" : "Antialias",
		"openlayer.6" : "Format",
		"openlayer.7" : "Styles",
		"openlayer.8" : "Filter",
		"openlayer.9" : "Search",
		"openlayer.10" : "Clear",
		"openother.1" : "Choose other...",
		"openother.2" : "Choose another editor",
		"openother.3" : "Select another editor to open this file",
		"openother.4" : "Warning, these editors do not declare to be supporting this file type, their behaviour maybe unpredictable!",
		"openother.5" : "Clear existing associations",
		"sm_editor.1" : "Sound Volume",
		"zoho_editor.1" : "Office Documents",
		"zoho_editor.2" : "Preview and edit office documents online",
		"zoho_editor.3" : "Word Document",
		"zoho_editor.4" : "Presentation Document",
		"zoho_editor.5" : "Spreadsheet Document",
		"powerfs.1" : "Creating archive, please wait",
		"powerfs.2" : "Reload current folder",
		"powerfs.3" : "Archive download should start automatically",
		"share_center.1" : "%s Public Download",
		"share_center.2" : "Click on the image to download <b>%s<\/b> to your hard drive",
		"share_center.3" : "Wrong password",
		"share_center.4" : "Enter the required password on click on the image to download <b>%s<\/b> to your hard drive",
		"share_center.5" : "password",
		"share_center.6" : "Stop Sharing",
		"share_center.7" : "Stopping the share will not remove the file. If you want to change the parameters, re-share the file.",
		"share_center.8" : "File is shared",
		"share_center.9" : "Use this button to stop sharing this folder",
		"share_center.10" : "Folder is shared",
		"share_center.11" : "Expiration",
		"share_center.12" : "Password",
		"share_center.13" : "Yes",
		"share_center.14" : "No",
		"share_center.15" : "File was download %s times",
		"share_center.16" : "reset",
		"share_center.17" : "Click to reset download counter",
		"share_center.18" : "Folder is shared as a new repository",
		"share_center.19" : "Shared repository options were successfully modified",
		"share_center.20" : "Ooops, the file you required could not be found! Maybe it was deleted or it is not shared with you anymore.",
		"skeleton.1" : "External Link",
		"skeleton.2" : "Link added by the action.skeleton plugin",
		"skeleton.3" : "Are you sure that you want to open %s in a new window?",
		"skeleton.4" : "Modal Link",
		"skeleton.5" : "Open the link in a modal dialog",
		"skeleton.6" : "Dynamic content",
		"skeleton.7" : "Loading content, please wait...",
		"updater.1" : "Upgrade...",
		"updater.2" : "Automatic version upgrade",
		"updater.3" : "Click on the button to start automatic upgrade procedure. Please check that the application folder is writeable before launching upgrade.",
		"updater.4" : "Start Upgrade",
		"updater.5" : "From 3.2.4",
		"updater.6" : "Import configuration data from 3.2.4",
		"updater.7" : "Simulate the data import",
		"updater.8" : "Enter full path (from server root) to the previous location, then run the simulation",
		"updater.9" : "Run real import now",
		"updater.10" : "This is a 'dry-run'. Please review the logs of all actions that will be performed, and if it's ok for you press 'Run real import now'",
		"updater.11" : "Migrate meta.serial",
		"updater.12" : "Old meta.serial plugin was removed and split into metastore.serial and meta.user",
		"updater.13" : "Simulate migration",
		"updater.14" : "Run migration now",
		"ftp_auth.1" : "Enter connexion data",
		"ftp_auth.2" : "Host",
		"ftp_auth.3" : "Optionnal Data",
		"ftp_auth.4" : "Start",
		"ftp_auth.5" : "Protocol",
		"ftp_auth.6" : "Charset",
		"ftp_auth.7" : "Active",
		"ftp_auth.8" : "Port",
		"languageLabel" : "English",
		"date_format" : "Y\/m\/d H:i",
		"byte_unit_symbol" : "b",
		"0" : "Last version",
		"1" : "Filename",
		"2" : "Size",
		"3" : "Type",
		"4" : "Modified",
		"5" : "Actions",
		"6" : "Rename",
		"7" : "Delete",
		"8" : "Directory",
		"9" : "Midi File",
		"10" : "Text file",
		"11" : "Javascript",
		"12" : "GIF picture",
		"13" : "JPG picture",
		"14" : "HTML page",
		"15" : "HTML page",
		"16" : "REAL file",
		"17" : "REAL file",
		"18" : "PERL script",
		"19" : "ZIP file",
		"20" : "WAV file",
		"21" : "PHP script",
		"22" : "PHP script",
		"23" : "File",
		"24" : "Parent directory",
		"25" : "Upload one or more files (max. ) in the directory : ",
		"26" : "Create a new directory in : ",
		"27" : "Upload",
		"28" : "Create a new file in : ",
		"29" : "Create",
		"30" : "Write a name for the directory then click on &quot;Create&quot;",
		"31" : "You must select a file",
		"32" : "Explore",
		"33" : "Error uploading file !",
		"34" : "The file",
		"35" : "has been successfully created in the directory",
		"36" : "It's size is",
		"37" : "You must write a valid name",
		"38" : "The directory",
		"39" : "has been created in",
		"40" : "This directory already exists (names are case insensitive)",
		"41" : "has been renamed to",
		"42" : "to",
		"43" : "already exists  (names are case insensitive)",
		"44" : "has been deleted",
		"45" : "directory",
		"46" : "file",
		"47" : "Do you really want to delete the",
		"48" : "OK",
		"49" : "CANCEL",
		"50" : "Exe file",
		"51" : "Text Editor",
		"52" : "Editing file",
		"53" : "Save",
		"54" : "Cancel",
		"55" : "has been modified",
		"56" : "BMP picture",
		"57" : "PNG picture",
		"58" : "CSS File",
		"59" : "MP3 File",
		"60" : "RAR File",
		"61" : "GZ File",
		"62" : "Root directory",
		"63" : "Log out",
		"64" : "XLS File",
		"65" : "Word File",
		"66" : "Copy",
		"67" : "Selected file",
		"68" : "Paste in",
		"69" : "Or select another directory",
		"70" : "Move",
		"71" : "This file already exists (names are case insensitive)",
		"72" : "The root path is not correct. Check it in the conf\/conf.php file",
		"73" : "has been copied into the directory",
		"74" : "has been moved into the directory",
		"75" : "The file users.txt is not in the directory prive",
		"76" : "This file has been removed",
		"77" : "Send",
		"78" : "Pass",
		"79" : "PDF File",
		"80" : "MOV File",
		"81" : "AVI File",
		"82" : "MPG File",
		"83" : "MPEG File",
		"84" : "Help",
		"85" : "Refresh",
		"86" : "Close",
		"87" : "Search",
		"88" : "Download",
		"89" : "Unable to open file",
		"90" : "Print",
		"91" : "FLASH File",
		"92" : "Language",
		"93" : "To choose your language, your browser must accept cookies.",
		"94" : "Login",
		"95" : "Select your language :",
		"96" : "Please select the destination folder in the tree : ",
		"97" : "Upload File",
		"98" : "Click anywhere on this box to close it.",
		"99" : "is not writeable. There might be a permission problem, please check with your administrator.",
		"100" : "Cannot find file ",
		"101" : "The origin and destination folders are the same!",
		"102" : "Error while creating file :",
		"103" : "Cannot find folder ",
		"104" : "Go to the given location",
		"105" : "Email an url to access directly to this location.",
		"106" : "Send Mail",
		"107" : "Your name and\/or email",
		"108" : "The destination email",
		"109" : "Clickable URL",
		"110" : "Add a comment",
		"111" : "The following email has been sent :",
		"112" : "Email sending failed : ",
		"113" : "The selection is empty!",
		"114" : "Unkown error happened during copy!",
		"115" : "The file has been saved successfully",
		"116" : "files",
		"117" : "The folder",
		"118" : "Download Multiple File",
		"119" : "Click on each file to download it.",
		"120" : "You are not allowed to delete the whole arborescence!",
		"121" : "Image File ",
		"122" : "Recycle Bin",
		"123" : "has been moved to the ",
		"124" : "Overwrite existing files?",
		"125" : "A file\/folder with that name already exists (names are case insensitive). Please choose another one!",
		"126" : "Thumbnails",
		"127" : "Size",
		"128" : "files selected.",
		"129" : "View",
		"130" : "Folders",
		"131" : "Details",
		"132" : "No file or folder",
		"133" : "Name",
		"134" : "Type",
		"135" : "Dimensions",
		"136" : "View Larger Image",
		"138" : "Last Modif.",
		"139" : "Edit Online",
		"140" : "Play whole folder",
		"141" : "Reading folder",
		"142" : "Logged as ",
		"143" : "Guest browsing. Log in.",
		"144" : "Not logged in.",
		"145" : "My Bookmarks",
		"146" : "Delete Bookmark",
		"147" : "Bookmarks",
		"148" : "Parent",
		"149" : "Refresh",
		"150" : "Display",
		"151" : "Switch display mode...",
		"152" : "Bookmark",
		"153" : "Add current location to MyBookmarks",
		"154" : "New Dir",
		"155" : "Create new directory",
		"156" : "New File",
		"157" : "Create new empty file",
		"158" : "Rename selected file or folder",
		"159" : "Copy selection to...",
		"160" : "Move selected files to ...",
		"161" : "Delete selected files.",
		"162" : "Edit text files online.",
		"163" : "Log in",
		"164" : "Log out",
		"165" : "Settings",
		"166" : "About",
		"167" : "About AjaXplorer",
		"168" : "Connect to AjaXplorer",
		"169" : "Disconnect from AjaXplorer",
		"170" : "Current Folder",
		"parent_access_key" : "P",
		"refresh_access_key" : "h",
		"list_access_key" : "L",
		"thumbs_access_key" : "T",
		"bookmarks_access_key" : "B",
		"upload_access_key" : "U",
		"folder_access_key" : "N",
		"file_access_key" : "F",
		"rename_access_key" : "R",
		"copy_access_key" : "C",
		"move_access_key" : "M",
		"delete_access_key" : "D",
		"edit_access_key" : "E",
		"view_access_key" : "V",
		"download_access_key" : "w",
		"settings_access_key" : "g",
		"about_access_key" : "A",
		"empty_recycle_access_key" : "y",
		"restore_access_key" : "o",
		"171" : "Browse",
		"172" : "Your Selection",
		"173" : "New folder name",
		"174" : "New file name",
		"175" : "Select destination folder",
		"176" : "The selected files will be moved to the Recycle Bin.",
		"177" : "Are you sure you want to permanently delete the selected files?",
		"178" : "Previous",
		"179" : "Next",
		"180" : "Enter login\/password",
		"181" : "Login",
		"182" : "Password",
		"183" : "Please select a destination folder different from the origin!",
		"184" : "Search in current folder and sub-folders",
		"185" : "Stop searching",
		"186" : "Image Preview",
		"187" : "Online Edition - ",
		"189" : "Edit My Preferences",
		"190" : "Language",
		"191" : "Default Display",
		"192" : "Details List",
		"193" : "Thumbnails",
		"194" : "Change Password",
		"195" : "User Preferences",
		"196" : "Your language differs from the current language!\\n Do you want to reload the page to switch language?",
		"197" : "Your password change will take effect after you logout.",
		"198" : "New",
		"199" : "Confirm",
		"200" : "Switch Repository to...",
		"201" : "Warning, some of your changes are not saved!\\n Are you sure you want to close?",
		"202" : "Warning, recursive copy!",
		"203" : "Destintation folder is the same as original folder!",
		"204" : "The file \"",
		"205" : "\" exceeds size limit (",
		"206" : "Mb).\\nIt will not be uploaded.",
		"207" : "You have no write permission on this folder",
		"208" : "You have no read permission on this folder",
		"209" : "Internal server error, please contact Administrator!",
		"210" : "Upload failed",
		"211" : "The file is too big!",
		"212" : "No file found on server!",
		"213" : "Error while copying file to current folder",
		"214" : "Browse",
		"215" : "Start Upload",
		"216" : "Clear",
		"217" : "Clear Completed",
		"218" : "Remove from queue",
		"219" : "Completed",
		"220" : "Empty",
		"221" : "Empty Recycle Bin",
		"222" : "Restore",
		"223" : "Restore file to its original location",
		"224" : "Go to",
		"225" : "Rename bookmark",
		"226" : "List",
		"227" : "Switch to details list view",
		"228" : "Thumbs",
		"229" : "Switch to thumbnails view",
		"230" : "Play",
		"231" : "Play Slideshow",
		"232" : "Stop",
		"233" : "Stop Slideshow",
		"234" : "View selected images",
		"235" : "Fullscreen",
		"236" : "Restore",
		"237" : "Old password",
		"238" : "Passwords differ!",
		"239" : "Please fill you current password",
		"240" : "Wrong password!",
		"241" : "Your preferences have been saved successfully!",
		"242" : "Svn Log",
		"svn_log_access_key" : "L",
		"243" : "Revision",
		"244" : "Author",
		"245" : "Date",
		"246" : "Message",
		"247" : "Extract",
		"248" : "Extract selection from zip to...",
		"249" : "Users",
		"250" : "Repositories",
		"251" : "Logs",
		"252" : "The total file size limit has been reached.",
		"253" : "There has been an HTTP Error:",
		"254" : "There has been an IO Error:",
		"255" : "These has been a Security Error:",
		"256" : "Uploaded",
		"257" : "Remove",
		"258" : "File count :",
		"259" : "Total size :",
		"260" : "bytes",
		"261" : "Remember Me",
		"262" : "One or more files appear to exist \\nalready in the destination folder.\\nWhat do you want to do?",
		"263" : "Overwrite",
		"264" : "Skip",
		"265" : "Files",
		"266" : "B",
		"267" : "Create",
		"268" : "Create a new table",
		"269" : "Structure",
		"270" : "Edit table structure",
		"271" : "Drop",
		"272" : "Drop open table",
		"273" : "Insert",
		"274" : "Insert a new record",
		"275" : "Are you sure you want to drop the selected table(s)?",
		"276" : "Edit selected record",
		"277" : "Delete selected records",
		"278" : "Are you sure you want to delete the selected record(s)?",
		"279" : "Tables",
		"280" : "Records",
		"281" : "Upload Limits",
		"282" : "Size per File",
		"283" : "Total Size",
		"284" : "Files Number",
		"285" : "Cannot find user, please try again.\\n Make sure your Caps Lock is not engaged!",
		"286" : "Your user is out of date with the current version, please use the upgrade procedure.",
		"287" : "File Permissions",
		"288" : "User",
		"289" : "Group",
		"290" : "All",
		"291" : "Apply recursively?",
		"292" : "Share...",
		"293" : "Create a public link to this file",
		"294" : "Link time expiration (in days) and password (leave empty if no password).",
		"295" : "Expiration",
		"296" : "Copy the URL below:",
		"297" : "New User",
		"298" : "Create a new user",
		"299" : "New...",
		"300" : "Create a new repository",
		"create_repo_accesskey" : "R",
		"create_user_accesskey" : "U",
		"301" : "Edit configuration",
		"302" : "Copy as Text",
		"303" : "Copy selection as tab-separated text.",
		"304" : "Back",
		"305" : "Go back to main page",
		"306" : "Too many items",
		"307" : "Fill optional fields",
		"308" : "Generate Link",
		"309" : "Generate",
		"310" : "Options",
		"311" : "Upload automatically when a file is added",
		"312" : "Uploader Options",
		"313" : "Compress...",
		"314" : "Compress selection to zip...",
		"315" : "Compress selection to",
		"316" : "Open in...",
		"open_with_access" : "e",
		"317" : "Source Editor",
		"318" : "CodePress source code viewer",
		"319" : "HTML Editor",
		"320" : "WYSIWYG editor for HTML",
		"321" : "Select",
		"322" : "Select the current file",
		"323" : "E-mail this URL",
		"324" : "No editor available",
		"325" : "Fit Best",
		"326" : "No Fit",
		"327" : "100%",
		"328" : "IMagick Viewer",
		"329" : "View pdf,svg and tif online",
		"330" : "Please wait while the pages are being rendered...",
		"331" : "Page",
		"332" : "of",
		"333" : "Pixlr image editor",
		"334" : "more",
		"335" : "Please enter a page number between 1 and ",
		"336" : "Sorry you cannot drop folders, drop only files!",
		"337" : "Auto start upload",
		"338" : "Auto close after upload",
		"339" : "Existing Files",
		"340" : "Alert",
		"341" : "File Info",
		"342" : "Folder Info",
		"343" : "Image Info",
		"344" : "Search on",
		"345" : "No version information could be retrieved",
		"346" : "Your version is up to date",
		"347" : "A new version (%s) is available! Visit %s",
		"348" : "A new repository has been shared.",
		"349" : "Warning, missing arguments",
		"350" : "A user that does not belong to you already exists with this name, please choose another name.",
		"351" : "You are not allowed to share elements to the public.",
		"352" : "A repository with the same name already exists, please choose another name.",
		"353" : "Target User",
		"354" : "Create a new user or choose one of your existing ones from the list.",
		"355" : "User Name",
		"356" : "User Pass",
		"357" : "Target Repository",
		"358" : "Choose a name for the shared element and assign access rights for your user.",
		"359" : "Label",
		"360" : "Rights",
		"361" : "Read",
		"362" : "Write",
		"363" : "Shared Elements",
		"364" : "You do not have the rights to perform this operation",
		"365" : "You are not allowed to upload more than %s files at once.",
		"366" : "This user does not have any active repository.",
		"367" : "You are not allowed to upload this type of file. Please choose among the following extensions : ",
		"368" : "Selection successfully extracted from archive %s to folder %s",
		"369" : "AjaXplorer Link",
		"370" : "AjaXplorer Public Download",
		"371" : "A password is required for this download",
		"372" : "Current Repository",
		"373" : "Destination",
		"374" : "You cannot copy folders across repositories",
		"375" : "Warning, you were inactive since more than __IDLE__, you will be logged out in __LOGOUT__",
		"376" : "Click anywhere to reactivate",
		"378" : "Warning, password is empty or too short!",
		"379" : "Unsafe word!",
		"380" : "Too short",
		"381" : "Very weak",
		"382" : "Weak",
		"383" : "Medium",
		"384" : "Strong",
		"385" : "Very strong",
		"386" : "You have failed logging in for 3 times.\\nFor your security, please fill the code that appear in the image.",
		"389" : "Please read the code below :",
		"390" : "Code",
		"391" : "No Repository",
		"392" : "Warning, AjaXplorer version has changed (now %s), please clear your browser cache and refresh the page to be sure that everything is functionnal!",
		"393" : "Warning, the names length must be under %s, this file's name will be truncated!",
		"394" : "Sorry, at the moment folder sharing is not possible using the current auth driver (users are not editable). File sharing is still possible though.",
		"395" : "The item you dropped seem to be a folder, and folders cannot be uploaded to server! Are you sure you want to upload?",
		"396" : "Auth. Method",
		"397" : "Download chunked",
		"398" : "Download selected file by pieces",
		"399" : "Enter the number of pieces you want to download, then click the button and click on each file to download them.",
		"400" : "Number of pieces :",
		"401" : "You can download and install the following software to join the pieces once on your computer : ",
		"402" : "http:\/\/www.hjsplit.org\/",
		"403" : "WebDAV Preferences",
		"404" : "You can use the WebDAV protocol to mount your AjaXplorer repositories as a 'network drive' on various clients, including Windows, Mac, iPhone, etc.",
		"405" : "Use the following URLS to access your repositories, with your username and the password you entered. Warning, this won't work until you set this feature as 'active' and you enter your password.",
		"406" : "Activate WebDAV shares",
		"407" : "Enter your password if it's the first time that you are activating webDAV shares, or if you want to re-type a new password :",
		"408" : "Activated WebDav shares successfully, do not forget to update your password if it's the first time!",
		"409" : "De-activated WebDav shares successfully",
		"410" : "Updated webDav password successfully",
		"411" : "Open",
		"412" : "Upload only",
		"413" : "Shared by",
		"414" : "Use arrows to navigate and +\/- to change zoom",
		"415" : "Toggle left pane visibility",
		"416" : "Left Pane",
		"leftpane_accesskey" : "L",
		"417" : "Add repository ...",
		"418" : "Create your own repository",
		"419" : "Loading templates...",
		"420" : "Templates",
		"421" : "New %s",
		"422" : "Please fill the required parameters. Fly over the field titles with your mouse to have more information.",
		"423" : "Delete repository",
		"424" : "Are you sure you want to delete this repository? The operation is irreversible.",
		"425" : "The repository is now created, it is added to your repository list, if you want to remove it, make sure to switch to another repository, then click on the red cross beside the repository name.",
		"426" : "There was an error while creating the repository",
		"427" : "There was an error while deleting the repository",
		"428" : "The repository was successfully deleted",
		"429" : "This is how the repository will appear in your list.",
		"430" : "Default Files",
		"431" : "Sample Template",
		"432" : "My Files",
		"433" : "ready",
		"434" : "sending",
		"435" : "done",
		"436" : "error",
		"437" : "Ooops, it seems that your security token has expired! Please %s by hitting refresh or F5 in your browser!",
		"438" : "reload the page",
		"439" : "Main Options",
		"440" : "Yes",
		"441" : "No",
		"httpdownloader.1" : "Remote DL",
		"httpdownloader.2" : "Download file(s) from remote server",
		"httpdownloader.3" : "m",
		"httpdownloader.4" : "Enter at least one URL pointing to a file that you want to download directly from an external HTTP server to the current folder. This action will be sent to the background and you will be able to continue using AjaXplorer during the download.",
		"httpdownloader.5" : "URL",
		"httpdownloader.6" : "Downloading",
		"httpdownloader.7" : "to server",
		"httpdownloader.8" : "File downloaded, reloading the client!",
		"httpdownloader.9" : "Generate Bookmarklet",
		"httpdownloader.10" : "Download to AjaXplorer",
		"httpdownloader.10a" : "Download to %s",
		"httpdownloader.10b" : "DL to %s",
		"httpdownloader.10c" : "DL to %s",
		"httpdownloader.10d" : "AjXp Download (%s)",
		"httpdownloader.11" : "Drag one of the following link to your bookmark bar : ",
		"httpdownloader.12" : "Trigger remote file download",
		"httpdownloader.13" : "From computer",
		"httpdownloader.14" : "From remote server",
		"httpdownloader.15" : "Or create a bookmark manually and use the code below as the link url : ",
		"httpdownloader.16" : "Drag me to your bookmark bar!",
		"httpdownloader.17" : "Download file",
		"httpdownloader.18" : "Partial file",
		"meta.exif.1" : "Exif GeoLocation",
		"meta.exif.2" : "Locate",
		"meta.simple_lock.1" : "Lock",
		"meta.simple_lock.2" : "Lock selected item",
		"meta.simple_lock.3" : "Unlock",
		"meta.simple_lock.4" : "Remove lock",
		"meta.simple_lock.5" : "This file is locked by another user, it is probably currently being edited, you are not allowed to modify it.",
		"meta.svn.1" : "Versions",
		"meta.svn.11" : "SVN Log of current folder",
		"meta.svn.2" : "Selection Log",
		"meta.svn.21" : "SVN Log of selected file or folder",
		"meta.svn.3" : "Switch to revision",
		"meta.user.1" : "File Meta Data",
		"meta.user.2" : "No Label",
		"meta.user.3" : "Remove Rating",
		"meta.user.4" : "Low",
		"meta.user.5" : "Todo",
		"meta.user.6" : "Personal",
		"meta.user.7" : "Work",
		"meta.user.8" : "Important",
		"index.lucene.1" : "Index Content",
		"index.lucene.2" : "Index folder content",
		"index.lucene.3" : "Running indexation in background",
		"index.lucene.4" : "The index seems to be locked, an indexation processs may be running. If not, please remove the .ajxp_lock file located in cache\/indexes.",
		"index.lucene.5" : "Indexation finished",
		"index.lucene.6" : "Warning, the repository is currently being indexed, please retry later.",
		"index.lucene.7" : "First indexing of this repository, please wait and retry your search",
		"index.lucene.8" : "Indexing %s in background",
		"index.lucene.9" : "Cannot find index for current repository! You should trigger the indexation of the data first!"
	},
	"password_min_length" : "8",
	"SECURE_TOKEN" : "92ec48f8e2b904e4d48e1452f4fb2c52",
	"streaming_supported" : "true",
	"theme" : "mybase"
}
